// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.ContractNameSpaces;
import schemagenerator.proxies.OdataComplexType;
import schemagenerator.proxies.OdataEnum;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CancelAddComplexTypePageAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __complexType;
	private schemagenerator.proxies.OdataComplexType complexType;

	public CancelAddComplexTypePageAction(IContext context, IMendixObject complexType)
	{
		super(context);
		this.__complexType = complexType;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.complexType = this.__complexType == null ? null : schemagenerator.proxies.OdataComplexType.initialize(getContext(), __complexType);

		// BEGIN USER CODE
		Core.rollback(getContext(), __complexType);
		IMendixObject cns = Core.retrieveByPath(getContext(), __complexType, OdataComplexType.MemberNames.OdataComplexType_ContractNameSpaces.toString()).get(0);
		String cnsName = cns.getValue(getContext(), ContractNameSpaces.MemberNames.ContractNameSpace.toString());
		String name = complexType.getComplexTypeName();
		name = cnsName + "." + name;
		complexType.setComplexTypeName(name);
		complexType.commit();
		FeedbackHelper.addCloseCallerFeedback(getContext());
		FeedbackHelper.addRefreshClass(getContext(), OdataComplexType.getType());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CancelAddComplexTypePageAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
