// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.ODataBasicTypes;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class EditActionParams__ extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __actionParams;
	private schemagenerator.proxies.ActionParams actionParams;

	public EditActionParams__(IContext context, IMendixObject actionParams)
	{
		super(context);
		this.__actionParams = actionParams;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.actionParams = this.__actionParams == null ? null : schemagenerator.proxies.ActionParams.initialize(getContext(), __actionParams);

		// BEGIN USER CODE
		//Set the type dropdown value for the params
		if (actionParams.getParameterDataType().contains(".")) {
			actionParams.setBaseType(ODataBasicTypes._Object);
			actionParams.commit();
		}
		else {
			String dataType = actionParams.getParameterDataType();
			ODataBasicTypes[] types = ODataBasicTypes.values();
			for (int i = 0; i < types.length; i++) {
				if (types[i].getCaption().equals(dataType)) {
					actionParams.setBaseType(types[i]);
					actionParams.commit();
				}
			}
		}

		/*FeedbackHelper.addOpenFormFeedback(
			getContext(),
			"SchemaGenerator/AddActionParamsPage",
			"Edit Action Parameter",
			IFeedback.FormTarget.MODAL,
			actionParams.getMendixObject().getId(),
			null
		);*/
		return actionParams.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EditActionParams__";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
