// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import schemagenerator.proxies.OperationMappingFile;
import schemagenerator.proxies.TemplateParameters;
import schemagenerator.proxies.View;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GenerateTreeForMappingAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __templateParams;
	private schemagenerator.proxies.TemplateParameters templateParams;

	public GenerateTreeForMappingAction(IContext context, IMendixObject templateParams)
	{
		super(context);
		this.__templateParams = templateParams;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.templateParams = this.__templateParams == null ? null : schemagenerator.proxies.TemplateParameters.initialize(getContext(), __templateParams);

		// BEGIN USER CODE
		View view = new View(getContext());
		IMendixObject mapping = Core.retrieveByPath(getContext(), __templateParams, TemplateParameters.MemberNames.TemplateParameters_OperationMappingFile.toString()).get(0);
		IMendixObject actions = Core.retrieveByPath(getContext(), mapping, OperationMappingFile.MemberNames.OperationMappingFile_OdataActions.toString()).get(0);
		Core.commit(getContext(), TcODataSchemaHelper.getTreeForOperationMappingParameters(getContext(), actions, view));
		templateParams.setTemplateParameters_View(getContext(), view);
		view.commit(getContext());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateTreeForMappingAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
