// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.LinkedList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import schemagenerator.proxies.ContractNameSpaces;
import schemagenerator.proxies.ODataSchema;
import schemagenerator.proxies.OdataActions;
import schemagenerator.proxies.OdataObject;
import schemagenerator.proxies.OperationMappingFile;
import schemagenerator.proxies.SelectionTreeNode;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetAllOdataEntitiesAction extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __node;
	private schemagenerator.proxies.SelectionTreeNode node;

	public GetAllOdataEntitiesAction(IContext context, IMendixObject node)
	{
		super(context);
		this.__node = node;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.node = this.__node == null ? null : schemagenerator.proxies.SelectionTreeNode.initialize(getContext(), __node);

		// BEGIN USER CODE
		IMendixObject view = Core.retrieveByPath(getContext(), __node, SelectionTreeNode.MemberNames.SelectionTreeNode_View.toString()).get(0);
		IMendixObject opMappingFile = Core.retrieveByPath(getContext(), view, OperationMappingFile.MemberNames.OperationMappingFile_View_Request.toString()).get(0);
		IMendixObject action = Core.retrieveByPath(getContext(), opMappingFile, OperationMappingFile.MemberNames.OperationMappingFile_OdataActions.toString()).get(0);
		List<IMendixObject> cnsList = Core.retrieveByPath(getContext(), action, OdataActions.MemberNames.OdataActions_ContractNameSpaces.toString());
		IMendixObject cns = null;
		if (cnsList.isEmpty()) {
			IMendixObject odataObject = Core.retrieveByPath(getContext(), action, OdataActions.MemberNames.OdataActions_OdataObject.toString()).get(0);
			cns = Core.retrieveByPath(getContext(), odataObject, OdataObject.MemberNames.OdataObject_ContractNameSpaces.toString()).get(0);
		}
		else {
			cns = cnsList.get(0);
		}
		IMendixObject schema = Core.retrieveByPath(getContext(), cns, ContractNameSpaces.MemberNames.ContractNameSpaces_ODataSchema.toString()).get(0);
		List<IMendixObject> allSchemas = TcODataSchemaHelper.getAllrefrencedSchemasAsMendixObjects(getContext(), schema);
		return TcODataSchemaHelper.getAllOdataObjects(getContext(), allSchemas);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetAllOdataEntitiesAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
