// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import schemagenerator.proxies.ContractNameSpaces;
import schemagenerator.proxies.OdataActions;
import schemagenerator.proxies.OdataObject;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserException;
import com.mendix.systemwideinterfaces.core.UserException.ExceptionCategory;

public class GetActionsAction extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __schema;
	private schemagenerator.proxies.ODataSchema schema;
	private IMendixObject __contactNameSpaceDropDown;
	private schemagenerator.proxies.ContractNameSpaceDropDown contactNameSpaceDropDown;

	public GetActionsAction(IContext context, IMendixObject schema, IMendixObject contactNameSpaceDropDown)
	{
		super(context);
		this.__schema = schema;
		this.__contactNameSpaceDropDown = contactNameSpaceDropDown;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.schema = this.__schema == null ? null : schemagenerator.proxies.ODataSchema.initialize(getContext(), __schema);

		this.contactNameSpaceDropDown = this.__contactNameSpaceDropDown == null ? null : schemagenerator.proxies.ContractNameSpaceDropDown.initialize(getContext(), __contactNameSpaceDropDown);

		// BEGIN USER CODE
		List<IMendixObject> contractNSList = Core.retrieveByPath(getContext(), __schema, ContractNameSpaces.MemberNames.ContractNameSpaces_ODataSchema.toString());
		IMendixObject selectedContractNS = null;
		for(IMendixObject contractNS : contractNSList) {
			if(contractNS.getValue(getContext(), ContractNameSpaces.MemberNames.ContractNameSpace.toString()).toString().equals(contactNameSpaceDropDown.getContractNameSpace(getContext()))) {
				selectedContractNS = contractNS;
				break;
			}
		}

		if(selectedContractNS == null)
			throw new UserException(ExceptionCategory.Custom, "The NameSpace Was not found");

		List<IMendixObject> allActions = new ArrayList<>();
		allActions.addAll(Core.retrieveByPath(getContext(), selectedContractNS, OdataActions.MemberNames.OdataActions_ContractNameSpaces.toString()));
		List<IMendixObject> allObjects = Core.retrieveByPath(getContext(), selectedContractNS, OdataObject.MemberNames.OdataObject_ContractNameSpaces.toString());
		for (IMendixObject odataObjects : allObjects) {
			allActions.addAll(Core.retrieveByPath(getContext(), odataObjects, OdataActions.MemberNames.OdataActions_OdataObject.toString()));
		}
		return allActions;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetActionsAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
