// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetComplexTypesForNameSpace extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __odataSchema;
	private schemagenerator.proxies.ODataSchema odataSchema;
	private IMendixObject __complexTypeDropDown;
	private schemagenerator.proxies.ContractNameSpaceDropDown complexTypeDropDown;

	public GetComplexTypesForNameSpace(IContext context, IMendixObject odataSchema, IMendixObject complexTypeDropDown)
	{
		super(context);
		this.__odataSchema = odataSchema;
		this.__complexTypeDropDown = complexTypeDropDown;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.odataSchema = this.__odataSchema == null ? null : schemagenerator.proxies.ODataSchema.initialize(getContext(), __odataSchema);

		this.complexTypeDropDown = this.__complexTypeDropDown == null ? null : schemagenerator.proxies.ContractNameSpaceDropDown.initialize(getContext(), __complexTypeDropDown);

		// BEGIN USER CODE
		List<IMendixObject> contractNSList = Core.retrieveByPath(getContext(), __odataSchema, "SchemaGenerator.ContractNameSpaces_ODataSchema");
		IMendixObject selectedContractNS = null;
		for(IMendixObject contractNS : contractNSList) {
			if(contractNS.getMember(getContext(), "ContractNameSpace").getValue(getContext()).toString().equals(complexTypeDropDown.getContractNameSpace(getContext()))) {
				selectedContractNS = contractNS;
				break;
			}
		}
		if(selectedContractNS == null)
			return new ArrayList<>();
		
		return Core.retrieveByPath(getContext(), selectedContractNS, "SchemaGenerator.OdataComplexType_ContractNameSpaces");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetComplexTypesForNameSpace";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
