// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import schemagenerator.proxies.OdataSchemaDocument;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;

public class GetDeployedFilesList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String ServicesJson;

	public GetDeployedFilesList(IContext context, java.lang.String ServicesJson)
	{
		super(context);
		this.ServicesJson = ServicesJson;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		JSONArray schemaInfo = new JSONObject(ServicesJson).getJSONArray("schemaInfo");
		
		List<IMendixObject> filesList = new ArrayList<IMendixObject>();
		for (int i = 0; i < schemaInfo.length(); i++)
		{
			OdataSchemaDocument ODataDoc = new OdataSchemaDocument(getContext());
			ODataDoc.setName(schemaInfo.getJSONObject(i).getString("schemaName"));
			ODataDoc.setmajorVersion(schemaInfo.getJSONObject(i).getString("schemaVersion"));
			ODataDoc.setminorVersion(schemaInfo.getJSONObject(i).getInt("minorVersion"));
			ODataDoc.setuid(schemaInfo.getJSONObject(i).getString("datasetUid"));
			ODataDoc.setdeployed(true);
			JSONArray releaseStatus = schemaInfo.getJSONObject(i).getJSONArray("releaseStatus");
			for(int index = 0; index < releaseStatus.length(); index++)
			{
				if(releaseStatus.getString(index).equals("Published"))
				{
					ODataDoc.setpublishedToDataHub(true);
					break;
				}
			}
			filesList.add(ODataDoc.getMendixObject());
		}
		
		return filesList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetDeployedFilesList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
