// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import schemagenerator.proxies.ContractNameSpaceDropDown;
import schemagenerator.proxies.ContractNameSpaces;
import schemagenerator.proxies.OdataEnum;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserException;
import com.mendix.systemwideinterfaces.core.UserException.ExceptionCategory;

public class GetEnumsAction extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __contractNameSpaceDropDown;
	private schemagenerator.proxies.ContractNameSpaceDropDown contractNameSpaceDropDown;
	private IMendixObject __odataSchema;
	private schemagenerator.proxies.ODataSchema odataSchema;

	public GetEnumsAction(IContext context, IMendixObject contractNameSpaceDropDown, IMendixObject odataSchema)
	{
		super(context);
		this.__contractNameSpaceDropDown = contractNameSpaceDropDown;
		this.__odataSchema = odataSchema;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.contractNameSpaceDropDown = this.__contractNameSpaceDropDown == null ? null : schemagenerator.proxies.ContractNameSpaceDropDown.initialize(getContext(), __contractNameSpaceDropDown);

		this.odataSchema = this.__odataSchema == null ? null : schemagenerator.proxies.ODataSchema.initialize(getContext(), __odataSchema);

		// BEGIN USER CODE
		List<IMendixObject> contractNSList = Core.retrieveByPath(getContext(), __odataSchema, ContractNameSpaces.MemberNames.ContractNameSpaces_ODataSchema.toString());
		IMendixObject selectedContractNS = null;
		for(IMendixObject contractNS : contractNSList) {
			if(contractNS.getValue(getContext(), ContractNameSpaces.MemberNames.ContractNameSpace.toString()).toString().equals(contractNameSpaceDropDown.getContractNameSpace(getContext()))) {
				selectedContractNS = contractNS;
				break;
			}
		}

		if(selectedContractNS == null)
			throw new UserException(ExceptionCategory.Custom, "The NameSpace Was not found");
		
		return Core.retrieveByPath(getContext(), selectedContractNS, OdataEnum.MemberNames.OdataEnum_ContractNameSpaces.toString());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetEnumsAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
