// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import schemagenerator.proxies.OperationMappingFile;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONObject;
import java.io.File;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;

public class GetOperationMapping extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __OperationInfo;
	private schemagenerator.proxies.OperationInfo OperationInfo;

	public GetOperationMapping(IContext context, IMendixObject OperationInfo)
	{
		super(context);
		this.__OperationInfo = OperationInfo;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.OperationInfo = this.__OperationInfo == null ? null : schemagenerator.proxies.OperationInfo.initialize(getContext(), __OperationInfo);

		// BEGIN USER CODE
		String path = OperationInfo.getPath(getContext());
		File serviceListFile = new File(Core.getConfiguration().getResourcesPath() , path);
		InputStream fileStream = FileUtils.openInputStream(serviceListFile);
		String fileJsonString = IOUtils.toString(fileStream);
		fileStream.close();
		JSONObject fileJson = new JSONObject(fileJsonString);
		
		String operationName = fileJson.optString("ServiceOperation");
		OperationMappingFile operationMapping = new OperationMappingFile(getContext());
		operationMapping.setOperationName(getContext(), operationName);

		operationMapping.setJSONModified(fileJsonString);
		return operationMapping.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetOperationMapping";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
