// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.OdataActions;
import schemagenerator.proxies.SelectionTreeNode;
import schemagenerator.proxies.View;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetSearchedTreeAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __view;
	private schemagenerator.proxies.View view;

	public GetSearchedTreeAction(IContext context, IMendixObject view)
	{
		super(context);
		this.__view = view;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.view = this.__view == null ? null : schemagenerator.proxies.View.initialize(getContext(), __view);

		// BEGIN USER CODE
		String searchString = view.getSearch(getContext());
		List<IMendixObject> nodes = Core.retrieveByPath(getContext(), __view, SelectionTreeNode.MemberNames.SelectionTreeNode_View.toString());
		ArrayList<IMendixIdentifier> tmpArray = new ArrayList<>();
		
		for (IMendixObject nodeMxObj : nodes) {
			if ((boolean)nodeMxObj.getValue(getContext(), SelectionTreeNode.MemberNames.Root.toString())) {
				List<IMendixObject> cnsNodes = Core.retrieveByPath(getContext(), nodeMxObj, SelectionTreeNode.MemberNames.SelectionTreeNode_View.toString());
				int noOfcnsRemoved = 0;
				for (IMendixObject cnsNodeMxObj : cnsNodes) {
					List<IMendixObject> leafNodes = Core.retrieveByPath(getContext(), cnsNodeMxObj, SelectionTreeNode.MemberNames.SelectionTreeNode_View.toString());
					int noOfObjectsRemoved = 0;
					for (IMendixObject leafNodeMxObj : leafNodes) {
						SelectionTreeNode leafNode = SelectionTreeNode.initialize(getContext(), leafNodeMxObj);
						if (!leafNode.getName(getContext()).contains(searchString)) {
							leafNode.setCSSClass(getContext(), "hidden");
							leafNode.commit();
							tmpArray.add(leafNode.getMendixObject().getId());
							// leafNode.setSelectionTreeNode_Children(getContext(), Collections.<SelectionTreeNode>emptyList());
							// Core.delete(getContext(), leafNodeMxObj);
							noOfObjectsRemoved++;
						}
					}
					if (noOfObjectsRemoved == leafNodes.size()) {
						SelectionTreeNode cnsNode = SelectionTreeNode.initialize(getContext(), cnsNodeMxObj);
						cnsNode.setSelectionTreeNode_Children(getContext(), Collections.<SelectionTreeNode>emptyList());
						cnsNode.setCSSClass(getContext(), "hidden");
						cnsNode.commit();
						tmpArray.add(cnsNode.getMendixObject().getId());
						// Core.delete(getContext(), cnsNodeMxObj);
						noOfcnsRemoved++;
					}
				}
				if (cnsNodes.size() == noOfcnsRemoved) {
					SelectionTreeNode node = SelectionTreeNode.initialize(getContext(), nodeMxObj);
					node.setCSSClass(getContext(), "hidden");
					node.commit(getContext());
					node.setSelectionTreeNode_View(getContext(), null);
					tmpArray.add(node.getMendixObject().getId());
					// Core.delete(getContext(), nodeMxObj);
				}
			}
		}
		FeedbackHelper.addRefreshClass(getContext(), SelectionTreeNode.getType());
		FeedbackHelper.addRefreshObjectListFeedback(getContext(), tmpArray);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetSearchedTreeAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
