// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.OdataSchemaDocument;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ImportOrOverwrite extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __interimServicesToBeImported;
	private schemagenerator.proxies.InterimServicesToBeImported interimServicesToBeImported;

	public ImportOrOverwrite(IContext context, IMendixObject interimServicesToBeImported)
	{
		super(context);
		this.__interimServicesToBeImported = interimServicesToBeImported;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.interimServicesToBeImported = this.__interimServicesToBeImported == null ? null : schemagenerator.proxies.InterimServicesToBeImported.initialize(getContext(), __interimServicesToBeImported);

		// BEGIN USER CODE
		FeedbackHelper.addCloseCallerFeedback(getContext());
		List<IMendixObject> odataSchemaDocs = Core.retrieveByPath(getContext(), __interimServicesToBeImported, "SchemaGenerator.OdataSchemaDocument_InterimServicesToBeImported");
		for (IMendixObject odataSchemaDocmObj : odataSchemaDocs) {
			OdataSchemaDocument odataSchemaDoc = OdataSchemaDocument.initialize(getContext(), odataSchemaDocmObj);
			String nameOfService = odataSchemaDoc.getName();
			String serviceVersion = odataSchemaDoc.getmajorVersion();
			List<IMendixObject> services = Core.retrieveXPathQuery(getContext(), "//SchemaGenerator.OdataSchemaDocument" + "[Name = '" + nameOfService + "'][majorVersion = '" + serviceVersion + "']");
			List<IMendixObject> toBeRemoved = new ArrayList<>();
			for (IMendixObject service : services) {
				if (service.getId().toLong() == odataSchemaDocmObj.getId().toLong())
					toBeRemoved.add(service);
			}
			services.removeAll(toBeRemoved);
			Core.delete(getContext(), services);
		}
		Core.commit(getContext(), odataSchemaDocs);
		interimServicesToBeImported.delete();

		FeedbackHelper.addRefreshClass(getContext(), OdataSchemaDocument.getType());

		FeedbackHelper.addTextMessageFeedback(
			getContext(),
			IFeedback.MessageType.INFO,
			"Services Imported Successfully",
			true
		);

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImportOrOverwrite";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
