// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.SelectionTreeNode;
import schemagenerator.proxies.SelectionTreeNodeHelper;
import schemagenerator.proxies.View;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class MapNodeForMappingJsonAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __odataObject;
	private schemagenerator.proxies.OdataObject odataObject;
	private IMendixObject __node;
	private schemagenerator.proxies.SelectionTreeNode node;

	public MapNodeForMappingJsonAction(IContext context, IMendixObject odataObject, IMendixObject node)
	{
		super(context);
		this.__odataObject = odataObject;
		this.__node = node;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.odataObject = this.__odataObject == null ? null : schemagenerator.proxies.OdataObject.initialize(getContext(), __odataObject);

		this.node = this.__node == null ? null : schemagenerator.proxies.SelectionTreeNode.initialize(getContext(), __node);

		// BEGIN USER CODE
		String newObjName = odataObject.getODataName();
		String[] names = node.getName().split("[:]");
		String finalName = "";
		if (names.length >= 2) {
			finalName = names[0] + ": " + newObjName;
		}
		else {
			finalName = names[0] + "\"" + newObjName + "\"";
		}
		node.setName(finalName);
		node.commit();
		FeedbackHelper.addRefreshObjectFeedback(getContext(), node.getMendixObject().getId());
		// FeedbackHelper.addRefreshClass(getContext(), SelectionTreeNode.getType());
		FeedbackHelper.addCloseCallerFeedback(getContext());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MapNodeForMappingJsonAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
