// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserException;
import com.mendix.systemwideinterfaces.core.UserException.ExceptionCategory;
import com.mendix.webui.CustomJavaAction;

public class NamingRules extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String Name;

	public NamingRules(IContext context, java.lang.String Name)
	{
		super(context);
		this.Name = Name;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		//Names can range from 1 to 255 characters.
		if(!(Name.length() >= 1 && Name.length() <= 255))
			throw new UserException(ExceptionCategory.Custom, "Invalid Name " + Name + "\nNames length is out of range.");
		
		//Names must begin with a letter of the alphabet.
		if(!Character.isLetterOrDigit(Name.charAt(0)))
			throw new UserException(ExceptionCategory.Custom, "Invalid Name " + Name + "\nNames must begin with a letter of the alphabet or number.");
		
		//After the first initial letter, OData names can also contain letters, numbers and (_)underscore character.
		//Spaces or special characters in names are not allowed
		if(!Name.matches("^\\w*$"))
			throw new UserException(ExceptionCategory.Custom, "Invalid Name " + Name + "\nNames can also contain letters, numbers and (_)underscore character. Spaces or special characters in names are not allowed.");
		return null;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "NamingRules";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
