// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.OdataActions;

public class RefreshEntityList extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String EntityToRefresh;

	public RefreshEntityList(IContext context, java.lang.String EntityToRefresh)
	{
		super(context);
		this.EntityToRefresh = EntityToRefresh;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		FeedbackHelper.addRefreshClass(getContext(), EntityToRefresh);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RefreshEntityList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
