// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import schemagenerator.proxies.OdataSchemaDocument;
import schemagenerator.proxies.constants.Constants;
import schemagenerator.proxies.microflows.Microflows;

public class ResolveExternalReference extends CustomJavaAction<java.lang.String>
{
	private java.lang.String URL;

	public ResolveExternalReference(IContext context, java.lang.String URL)
	{
		super(context);
		this.URL = URL;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		String CAPABLITIES_URI = "http://localhost/Org.OData.Capabilities.V1/v4.0/Org.OData.Capabilities.V1.xml";
		if(URL.equals(CAPABLITIES_URI))
			return null;
		
		String relativePath = URL.split("localhost/")[1];
		
		String[] names = relativePath.split(Constants.getAppendInFileName());
		
		OdataSchemaDocument odataSchemaDocument = Microflows.retriveOdataSchemaDocument(getContext(), names[0], names[1]);

		String resolvedSchemaString;
		if(odataSchemaDocument == null)
		{
			OdataSchemaDocument ODataDoc = new OdataSchemaDocument(getContext());
			ODataDoc.setName(names[0]);
			ODataDoc.setmajorVersion(names[1]);
			resolvedSchemaString = Microflows.getDeployedServicesContent(getContext(), ODataDoc);
		}
		else
		{
			resolvedSchemaString = TcODataSchemaHelper.extractSchemaJsonString(getContext(), odataSchemaDocument);
		}
		
		return resolvedSchemaString;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ResolveExternalReference";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
