// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.OdataActions;
import schemagenerator.proxies.ReturnType;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SaveOutputAndShowActionDetailsPageAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __odataAction;
	private schemagenerator.proxies.OdataActions odataAction;

	public SaveOutputAndShowActionDetailsPageAction(IContext context, IMendixObject odataAction)
	{
		super(context);
		this.__odataAction = odataAction;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.odataAction = this.__odataAction == null ? null : schemagenerator.proxies.OdataActions.initialize(getContext(), __odataAction);

		// BEGIN USER CODE
		ReturnType returnType = new ReturnType(getContext());
		returnType.setReturnType_OdataActions(odataAction);
		returnType.setIsCollection(false);
		returnType.setIsRequired(false);
		// returnType.setBaseType(ODataBasicTypesWithVoid._Void.getCaption());
		returnType.commit();

		//odataAction.setReturnBaseType(ODataBasicTypesWithVoid._Void);

		odataAction.commit();
		// (new SaveNewActionAction(getContext(), odataAction.getMendixObject())).executeAction();
		FeedbackHelper.addCloseCallerFeedback(getContext());
		FeedbackHelper.addRefreshClass(getContext(), OdataActions.getType());

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SaveOutputAndShowActionDetailsPageAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
