// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.ComplexTypeAttribute;
import schemagenerator.proxies.ContractNameSpaces;
import schemagenerator.proxies.ODataBasicTypes;
import schemagenerator.proxies.OdataComplexType;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SaveComplexTypeAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __complexType;
	private schemagenerator.proxies.OdataComplexType complexType;

	public SaveComplexTypeAction(IContext context, IMendixObject complexType)
	{
		super(context);
		this.__complexType = complexType;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.complexType = this.__complexType == null ? null : schemagenerator.proxies.OdataComplexType.initialize(getContext(), __complexType);

		// BEGIN USER CODE
//		List<IMendixObject> listOfBaseTypes = Core.retrieveByPath(getContext(), __complexType, OdataComplexType.MemberNames.OdataComplexType_ODataFullyQualifiedName.toString());
//		if (!listOfBaseTypes.isEmpty()) {
//			IMendixObject baseTypeFQNmObj = listOfBaseTypes.get(0);
//			String baseTypeFQN = baseTypeFQNmObj.getMember(getContext(), ODataFullyQualifiedName.MemberNames.FQN.toString()).getValue(getContext()).toString();
//			complexType.setBaseComplexType(getContext(), baseTypeFQN);
//		}
		IMendixObject cns = Core.retrieveByPath(getContext(), __complexType, OdataComplexType.MemberNames.OdataComplexType_ContractNameSpaces.toString()).get(0);
		String contractName = cns.getMember(getContext(), ContractNameSpaces.MemberNames.ContractNameSpace.toString()).getValue(getContext()).toString();
		complexType.setComplexTypeName(getContext(), contractName + "." + complexType.getComplexTypeName());
		complexType.commit(getContext());
		FeedbackHelper.addCloseCallerFeedback(getContext());
		FeedbackHelper.addRefreshClass(getContext(), OdataComplexType.getType());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SaveComplexTypeAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
