// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.ComplexTypeAttribute;
import schemagenerator.proxies.ODataBasicTypes;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SaveComplexTypeAttributeAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __complexTypeAttribute;
	private schemagenerator.proxies.ComplexTypeAttribute complexTypeAttribute;

	public SaveComplexTypeAttributeAction(IContext context, IMendixObject complexTypeAttribute)
	{
		super(context);
		this.__complexTypeAttribute = complexTypeAttribute;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.complexTypeAttribute = this.__complexTypeAttribute == null ? null : schemagenerator.proxies.ComplexTypeAttribute.initialize(getContext(), __complexTypeAttribute);

		// BEGIN USER CODE
		if (!complexTypeAttribute.getBaseType(getContext()).equals(ODataBasicTypes._Object)) {
			complexTypeAttribute.setAttributeDataType(getContext(), complexTypeAttribute.getBaseType(getContext()).getCaption());
		}
		complexTypeAttribute.commit(getContext());
		FeedbackHelper.addCloseCallerFeedback(getContext());
		FeedbackHelper.addRefreshClass(getContext(), ComplexTypeAttribute.getType());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SaveComplexTypeAttributeAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
