// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.OdataEnum;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ShowEditAddEnumPageAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __odataEnum;
	private schemagenerator.proxies.OdataEnum odataEnum;

	public ShowEditAddEnumPageAction(IContext context, IMendixObject odataEnum)
	{
		super(context);
		this.__odataEnum = odataEnum;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.odataEnum = this.__odataEnum == null ? null : schemagenerator.proxies.OdataEnum.initialize(getContext(), __odataEnum);

		// BEGIN USER CODE
		odataEnum.setName(odataEnum.getName(getContext()).split("[.]")[1]);
		odataEnum.commit();
		FeedbackHelper.addOpenFormFeedback(
			getContext(),
			"SchemaGenerator/AddEnumPage",
			"Edit Enum",
			IFeedback.FormTarget.MODAL,
			odataEnum.getMendixObject().getId(),
			null
		);
		FeedbackHelper.addRefreshClass(getContext(), OdataEnum.getType());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ShowEditAddEnumPageAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
