// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.ContractNameSpaces;
import schemagenerator.proxies.OdataComplexType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserException;
import com.mendix.systemwideinterfaces.core.UserException.ExceptionCategory;

public class ShowAddComplexTypePageAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __odataSchema;
	private schemagenerator.proxies.ODataSchema odataSchema;
	private IMendixObject __contractNameSpaceDropDown;
	private schemagenerator.proxies.ContractNameSpaceDropDown contractNameSpaceDropDown;

	public ShowAddComplexTypePageAction(IContext context, IMendixObject odataSchema, IMendixObject contractNameSpaceDropDown)
	{
		super(context);
		this.__odataSchema = odataSchema;
		this.__contractNameSpaceDropDown = contractNameSpaceDropDown;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.odataSchema = this.__odataSchema == null ? null : schemagenerator.proxies.ODataSchema.initialize(getContext(), __odataSchema);

		this.contractNameSpaceDropDown = this.__contractNameSpaceDropDown == null ? null : schemagenerator.proxies.ContractNameSpaceDropDown.initialize(getContext(), __contractNameSpaceDropDown);

		// BEGIN USER CODE
		List<IMendixObject> contractNSList = Core.retrieveByPath(getContext(), __odataSchema, "SchemaGenerator.ContractNameSpaces_ODataSchema");
		IMendixObject selectedContractNS = null;
		for(IMendixObject contractNS : contractNSList) {
			if(contractNS.getMember(getContext(), "ContractNameSpace").getValue(getContext()).toString().equals(contractNameSpaceDropDown.getContractNameSpace(getContext()))) {
				selectedContractNS = contractNS;
				break;
			}
		}
		if(selectedContractNS == null)
			throw new UserException(ExceptionCategory.Custom, "The NameSpace Was not found");

		OdataComplexType odataComplexType = new OdataComplexType(getContext());
		odataComplexType.setOdataComplexType_ContractNameSpaces(getContext(), ContractNameSpaces.initialize(getContext(), selectedContractNS));
		
		FeedbackHelper.addOpenFormFeedback(
			getContext(),
			"SchemaGenerator/AddComplexTypePage",
			IFeedback.FormTarget.MODAL,
			odataComplexType.getMendixObject().getId(),
			null
		);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ShowAddComplexTypePageAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
