// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.ContractNameSpaces;
import schemagenerator.proxies.OdataActions;
import schemagenerator.proxies.View;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ShowSelectBoundEntityForActionsPageAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __odataAction;
	private schemagenerator.proxies.OdataActions odataAction;

	public ShowSelectBoundEntityForActionsPageAction(IContext context, IMendixObject odataAction)
	{
		super(context);
		this.__odataAction = odataAction;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.odataAction = this.__odataAction == null ? null : schemagenerator.proxies.OdataActions.initialize(getContext(), __odataAction);

		// BEGIN USER CODE
		IMendixObject cns = Core.retrieveByPath(getContext(), __odataAction, OdataActions.MemberNames.OdataActions_ContractNameSpaces.toString()).get(0);
		IMendixObject schema = Core.retrieveByPath(getContext(), cns, ContractNameSpaces.MemberNames.ContractNameSpaces_ODataSchema.toString()).get(0);
		View view = new View(getContext());
		Core.commit(getContext(), TcODataSchemaHelper.getObjectSelectionTreeForSchemaGenreation(getContext(), schema, false, true, false, __odataAction.getId(), view));
		view.setViewForObjectType(getContext(), odataAction.entityName);
		view.setIsforBound(getContext(), true);
		odataAction.setOdataActions_View(getContext(), view);
		view.commit(getContext());
		FeedbackHelper.addOpenFormFeedback(
			getContext(),
			"SchemaGenerator/SelectBoundEntityForActions",
			IFeedback.FormTarget.MODAL,
			view.getMendixObject().getId(),
			null
		);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ShowSelectBoundEntityForActionsPageAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
