// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback;
import com.mendix.webui.CustomJavaAction;
import com.mendix.webui.FeedbackHelper;
import schemagenerator.proxies.ContractNameSpaceDropDown;
import schemagenerator.proxies.ContractNameSpaces;
import schemagenerator.proxies.OdataEnum;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserException;
import com.mendix.systemwideinterfaces.core.UserException.ExceptionCategory;

public class ShowAddEnumPageAction extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __odataSchema;
	private schemagenerator.proxies.ODataSchema odataSchema;
	private IMendixObject __contractNamesapceDropDown;
	private schemagenerator.proxies.ContractNameSpaceDropDown contractNamesapceDropDown;

	public ShowAddEnumPageAction(IContext context, IMendixObject odataSchema, IMendixObject contractNamesapceDropDown)
	{
		super(context);
		this.__odataSchema = odataSchema;
		this.__contractNamesapceDropDown = contractNamesapceDropDown;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.odataSchema = this.__odataSchema == null ? null : schemagenerator.proxies.ODataSchema.initialize(getContext(), __odataSchema);

		this.contractNamesapceDropDown = this.__contractNamesapceDropDown == null ? null : schemagenerator.proxies.ContractNameSpaceDropDown.initialize(getContext(), __contractNamesapceDropDown);

		// BEGIN USER CODE
		List<IMendixObject> contractNSList = Core.retrieveByPath(getContext(), __odataSchema, ContractNameSpaces.MemberNames.ContractNameSpaces_ODataSchema.toString());
		IMendixObject selectedContractNS = null;
		for(IMendixObject contractNS : contractNSList) {
			if(contractNS.getValue(getContext(), ContractNameSpaces.MemberNames.ContractNameSpace.toString()).toString().equals(contractNamesapceDropDown.getContractNameSpace(getContext()))) {
				selectedContractNS = contractNS;
				break;
			}
		}

		if(selectedContractNS == null)
			throw new UserException(ExceptionCategory.Custom, "The NameSpace Was not found");
		
		OdataEnum odataEnum = new OdataEnum(getContext());
		odataEnum.setOdataEnum_ContractNameSpaces(getContext(), ContractNameSpaces.initialize(getContext(), selectedContractNS));
		FeedbackHelper.addOpenFormFeedback(
			getContext(),
			"SchemaGenerator/AddEnumPage",
			IFeedback.FormTarget.MODAL,
			odataEnum.getMendixObject().getId(),
			null
		);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ShowAddEnumPageAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
