// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package schemagenerator.actions;

import java.util.List;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ValidateNamespace extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __OdataSchema;
	private schemagenerator.proxies.ODataSchema OdataSchema;

	public ValidateNamespace(IContext context, IMendixObject OdataSchema)
	{
		super(context);
		this.__OdataSchema = OdataSchema;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.OdataSchema = this.__OdataSchema == null ? null : schemagenerator.proxies.ODataSchema.initialize(getContext(), __OdataSchema);

		// BEGIN USER CODE
		try {
			List<IMendixObject> contractNSList = Core.retrieveByPath(getContext(), __OdataSchema, "SchemaGenerator.ContractNameSpaces_ODataSchema");
			boolean throwErr = true;
			for(IMendixObject contractNS : contractNSList)
			{
				String contractNSName = contractNS.getMember(getContext(), "ContractNameSpace").getValue(getContext()).toString();
				if(contractNS.getMember(getContext(), "InheritedObject").getValue(getContext()).toString().equals("false"))
				{
					NamingRules namingRules = new NamingRules(getContext(), contractNSName);
					namingRules.executeAction();
					throwErr = false;
				}
			}
			
			if(throwErr)
				throw new Exception("Please add atlease one new namespace in the service.");
		} catch (Exception e) {
			throw e;
		}
		return null;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ValidateNamespace";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
