POST /tc/RestServices/Workflow-2014-06-Workflow/performAction3 HTTP/1.1
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Log-Correlation-ID: DESKTOP-QNV01H1.44574.01.admin.00015
User-Agent: Jakarta Commons-HttpClient/3.1
Host: 124.70.31.150:7001
Cookie: JSESSIONID=u7pWo8QiOow6GQOvIeLP5plaBqjLE76k6jLngFG93YBwBD9qRDHU!-129683720
Content-Length: 1630

<?xml version="1.0" encoding="UTF-8"?>
<RequestEnvelope xmlns="http://teamcenter.com/Schemas/Soa/2006-09/ClientContext"><header><stringState name="objectPropertyPolicy" value="Default"/><stringState name="clientID" value="DESKTOP-QNV01H1.03448.01"/><stringState name="timezone" value="28800000"/><stringState name="logCorrelationID" value="DESKTOP-QNV01H1.44574.01.admin.00015"/><stringState name="reqServerID" value="tcserver45@PoolA@20428@ecs-mendix"/><stringState name="clientVersion" value="V11000.2.0.20150715.00"/><integerState name="baseSchemaVersion" value="2"/><booleanState name="allowPaging" value="true"/><booleanState name="refreshPOM" value="true"/></header><body><bodystring><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<ns7:PerformAction3Input xmlns:ns8="http://teamcenter.com/Schemas/Workflow/2014-10/Workflow" xmlns:ns4="http://teamcenter.com/Schemas/Workflow/2010-09/Workflow" xmlns:ns5="http://teamcenter.com/Schemas/Workflow/2012-10/Workflow" xmlns:ns2="http://teamcenter.com/Schemas/Soa/2006-03/Base" xmlns="http://teamcenter.com/Schemas/Workflow/2007-06/Workflow" xmlns:ns9="http://teamcenter.com/Schemas/Workflow/2015-07/Workflow" xmlns:ns7="http://teamcenter.com/Schemas/Workflow/2014-06/Workflow" xmlns:ns6="http://teamcenter.com/Schemas/Workflow/2013-05/Workflow" xmlns:ns3="http://teamcenter.com/Schemas/Workflow/2008-06/Workflow"><ns7:input clientId="" action="SOA_EPM_approve_action" password="" supportingValue="SOA_EPM_approve"><ns7:actionableObject uid="QanN69FA5p7SJC"/><ns7:supportingObject uid="Q6gN69FA5p7SJC"/></ns7:input></ns7:PerformAction3Input>]]></bodystring></body></RequestEnvelope>

HTTP/1.1 200 OK
Date: Wed, 28 Dec 2022 02:51:20 GMT
Transfer-Encoding: chunked
Content-Type: text/xml


<ns0:ServiceData xmlns:ns0="http://teamcenter.com/Schemas/Soa/2006-03/Base">
<ns0:updatedObjs uid="wNiJ_l7z5p7SJC"/>
<ns0:updatedObjs uid="wNmJ_l7z5p7SJC"/>
<ns0:updatedObjs uid="QanN69FA5p7SJC"/>
<ns0:updatedObjs uid="QWpN69FA5p7SJC"/>
<ns0:updatedObjs uid="QWkN69FA5p7SJC"/>
<ns0:updatedObjs uid="Q6gN69FA5p7SJC"/>
<ns0:updatedObjs uid="QWrN69FA5p7SJC"/>
<ns0:updatedObjs uid="QapN69FA5p7SJC"/>
<ns0:updatedObjs uid="QarN69FA5p7SJC"/>
<ns0:updatedObjs uid="gCkN69FA5p7SJC"/>
<ns0:plainObjs uid="QanN69FA5p7SJC"/>
<ns0:dataObjects objectID="xwkJeWDN5p7SJC" uid="xwkJeWDN5p7SJC" className="EPMTaskTemplate" type="EPMPerformSignoffTaskTemplate">
<ns0:properties name="template_name" uiValue="perform-signoffs">
<ns0:values value="perform-signoffs"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="Q6gN69FA5p7SJC" uid="Q6gN69FA5p7SJC" className="Signoff" type="Signoff">
<ns0:properties name="comments" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="decision" uiValue="Approve">
<ns0:values value="89"/></ns0:properties>
<ns0:properties name="decision_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:21+08:00"/></ns0:properties>
<ns0:properties name="fnd0Performer" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="QWpN69FA5p7SJC" uid="QWpN69FA5p7SJC" className="EPMTask" type="EPMReviewTask">
<ns0:properties name="active_surrogate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="archive_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="attachments"></ns0:properties>
<ns0:properties name="backup_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0ActualDuration" uiValue="43">
<ns0:values value="43"/></ns0:properties>
<ns0:properties name="fnd0AssigneeOrigin" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0EndDate" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:38+08:00"/></ns0:properties>
<ns0:properties name="fnd0InProcess" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="date_released" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Assigner" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="comments" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="creation_date" uiValue="26-Dec-2022 18:07">
<ns0:values value="2022-12-26T18:07:58+08:00"/></ns0:properties>
<ns0:properties name="due_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="ead_paragraph"></ns0:properties>
<ns0:properties name="fnd0Performer" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="fnd0Priority" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="job_name" uiValue="000022/A;1-...............1">
<ns0:values value="000022/A;1-...............1"/></ns0:properties>
<ns0:properties name="late_flag" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="parent_task" uiValue="CY-FLW-014/..................">
<ns0:values value="QWkN69FA5p7SJC"/></ns0:properties>
<ns0:properties name="revision_limit" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="last_mod_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="secure_task" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="signoff_quorum" uiValue="-100">
<ns0:values value="-100"/></ns0:properties>
<ns0:properties name="task_result" uiValue="Approved">
<ns0:values value="Approved"/></ns0:properties>
<ns0:properties name="task_template" uiValue="......">
<ns0:values value="xAsJeWDN5p7SJC"/></ns0:properties>
<ns0:properties name="fnd0StartedTasks"></ns0:properties>
<ns0:properties name="parent_processes"></ns0:properties>
<ns0:properties name="viewed_by"></ns0:properties>
<ns0:properties name="license_list"></ns0:properties>
<ns0:properties name="wait_for_all_reviewers" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="wso_thread" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Instructions" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="owning_project" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="project_list"></ns0:properties>
<ns0:properties name="gov_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="ip_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0LatestEPMTaskOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0StartDate" uiValue="28-Dec-2022 10:07">
<ns0:values value="2022-12-28T10:07:47+08:00"/></ns0:properties>
<ns0:properties name="named_acl" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="object_name" uiValue="......">
<ns0:values value="......"/></ns0:properties>
<ns0:properties name="owning_organization" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="real_state" uiValue="Completed">
<ns0:values value="Completed"/></ns0:properties>
<ns0:properties name="recipients"></ns0:properties>
<ns0:properties name="priority" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0IsRevisionDiscontinued" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0LatestTargetOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:38+08:00"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_string" uiValue="......">
<ns0:values value="......"/></ns0:properties>
<ns0:properties name="object_type" uiValue="Review Task">
<ns0:values value="EPMReviewTask"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="QanN69FA5p7SJC" uid="QanN69FA5p7SJC" className="EPMTask" type="EPMPerformSignoffTask">
<ns0:properties name="archive_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="attachments"></ns0:properties>
<ns0:properties name="backup_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="active_surrogate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="comments" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="date_released" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="ead_paragraph"></ns0:properties>
<ns0:properties name="due_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="creation_date" uiValue="26-Dec-2022 18:07">
<ns0:values value="2022-12-26T18:07:58+08:00"/></ns0:properties>
<ns0:properties name="fnd0ActualDuration" uiValue="43">
<ns0:values value="43"/></ns0:properties>
<ns0:properties name="fnd0AssigneeOrigin" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0EndDate" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:33+08:00"/></ns0:properties>
<ns0:properties name="fnd0Assigner" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0InProcess" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0IsRevisionDiscontinued" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Instructions" uiValue="Signoff team perform their signoffs.">
<ns0:values value="Signoff team perform their signoffs."/></ns0:properties>
<ns0:properties name="object_name" uiValue="perform-signoffs">
<ns0:values value="perform-signoffs"/></ns0:properties>
<ns0:properties name="owning_organization" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Performer" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="job_name" uiValue="000022/A;1-...............1">
<ns0:values value="000022/A;1-...............1"/></ns0:properties>
<ns0:properties name="fnd0LatestEPMTaskOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0LatestTargetOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Priority" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0StartedTasks"></ns0:properties>
<ns0:properties name="late_flag" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="ip_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="license_list"></ns0:properties>
<ns0:properties name="fnd0StartDate" uiValue="28-Dec-2022 10:07">
<ns0:values value="2022-12-28T10:07:50+08:00"/></ns0:properties>
<ns0:properties name="gov_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="last_mod_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="named_acl" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="project_list"></ns0:properties>
<ns0:properties name="recipients"></ns0:properties>
<ns0:properties name="secure_task" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="owning_project" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="signoff_quorum" uiValue="-100">
<ns0:values value="-100"/></ns0:properties>
<ns0:properties name="task_result" uiValue="Approved">
<ns0:values value="Approved"/></ns0:properties>
<ns0:properties name="viewed_by"></ns0:properties>
<ns0:properties name="root_target_attachments">
<ns0:values value="wZiJ_pMM5p7SJC"/>
<ns0:values value="AKpJ_pMM5p7SJC"/>
<ns0:values value="AOuJ_pMM5p7SJC"/>
<ns0:values value="AWjJ_pMM5p7SJC"/>
<ns0:values value="wxuJ_pMM5p7SJC"/><ns0:uiValues>000022/A;1-...............1</ns0:uiValues><ns0:uiValues>JTModel.jt</ns0:uiValues><ns0:uiValues>......word.docx</ns0:uiValues><ns0:uiValues>......excel.xlsx</ns0:uiValues><ns0:uiValues>......pdf.pdf</ns0:uiValues></ns0:properties>
<ns0:properties name="wso_thread" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="parent_task" uiValue="......">
<ns0:values value="QWpN69FA5p7SJC"/></ns0:properties>
<ns0:properties name="real_state" uiValue="Completed">
<ns0:values value="Completed"/></ns0:properties>
<ns0:properties name="wait_for_all_reviewers" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="task_template" uiValue="perform-signoffs">
<ns0:values value="xohJeWDN5p7SJC"/></ns0:properties>
<ns0:properties name="priority" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="revision_limit" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="parent_processes"></ns0:properties>
<ns0:properties name="signoff_attachments">
<ns0:values value="Q6gN69FA5p7SJC"/><ns0:uiValues></ns0:uiValues></ns0:properties>
<ns0:properties name="object_type" uiValue="Perform Signoff Task">
<ns0:values value="EPMPerformSignoffTask"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="object_string" uiValue="perform-signoffs">
<ns0:values value="perform-signoffs"/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:33+08:00"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="QapN69FA5p7SJC" uid="QapN69FA5p7SJC" className="EPMTask" type="EPMSelectSignoffTask">
<ns0:properties name="active_surrogate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="archive_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="backup_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="attachments"></ns0:properties>
<ns0:properties name="due_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="date_released" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="ead_paragraph"></ns0:properties>
<ns0:properties name="comments" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0ActualDuration" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0AssigneeOrigin" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="fnd0Assigner" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="creation_date" uiValue="26-Dec-2022 18:07">
<ns0:values value="2022-12-26T18:07:58+08:00"/></ns0:properties>
<ns0:properties name="fnd0Instructions" uiValue="Choose signoff team.">
<ns0:values value="Choose signoff team."/></ns0:properties>
<ns0:properties name="fnd0LatestTargetOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0StartDate" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:41+08:00"/></ns0:properties>
<ns0:properties name="ip_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="job_name" uiValue="000022/A;1-...............1">
<ns0:values value="000022/A;1-...............1"/></ns0:properties>
<ns0:properties name="last_mod_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="license_list"></ns0:properties>
<ns0:properties name="fnd0Priority" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="named_acl" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="object_name" uiValue="select-signoff-team">
<ns0:values value="select-signoff-team"/></ns0:properties>
<ns0:properties name="fnd0InProcess" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0EndDate" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:44+08:00"/></ns0:properties>
<ns0:properties name="fnd0Performer" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="fnd0StartedTasks"></ns0:properties>
<ns0:properties name="late_flag" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0IsRevisionDiscontinued" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0LatestEPMTaskOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0PerformForm" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="gov_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="secure_task" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="signoff_quorum" uiValue="-100">
<ns0:values value="-100"/></ns0:properties>
<ns0:properties name="real_state" uiValue="Completed">
<ns0:values value="Completed"/></ns0:properties>
<ns0:properties name="viewed_by"></ns0:properties>
<ns0:properties name="project_list"></ns0:properties>
<ns0:properties name="priority" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="wait_for_all_reviewers" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="parent_processes"></ns0:properties>
<ns0:properties name="wso_thread" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="parent_task" uiValue="......">
<ns0:values value="QWrN69FA5p7SJC"/></ns0:properties>
<ns0:properties name="revision_limit" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="owning_organization" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="recipients"></ns0:properties>
<ns0:properties name="task_template" uiValue="select-signoff-team">
<ns0:values value="xskJeWDN5p7SJC"/></ns0:properties>
<ns0:properties name="owning_project" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="task_result" uiValue="Completed">
<ns0:values value="Completed"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:44+08:00"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="object_type" uiValue="Select Signoff Team Task">
<ns0:values value="EPMSelectSignoffTask"/></ns0:properties>
<ns0:properties name="object_string" uiValue="select-signoff-team">
<ns0:values value="select-signoff-team"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="wNiJ_l7z5p7SJC" uid="wNiJ_l7z5p7SJC" className="TaskInbox" type="TaskInbox">
<ns0:properties name="last_mod_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:48+08:00"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_type" uiValue="Inbox">
<ns0:values value="TaskInbox"/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="object_string" uiValue="admin (admin) Inbox">
<ns0:values value="admin (admin) Inbox"/></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="QWrN69FA5p7SJC" uid="QWrN69FA5p7SJC" className="EPMTask" type="EPMReviewTask">
<ns0:properties name="active_surrogate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="archive_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="creation_date" uiValue="26-Dec-2022 18:07">
<ns0:values value="2022-12-26T18:07:58+08:00"/></ns0:properties>
<ns0:properties name="fnd0AssigneeOrigin" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Assigner" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="backup_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="attachments"></ns0:properties>
<ns0:properties name="comments" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="date_released" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="due_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="ead_paragraph"></ns0:properties>
<ns0:properties name="fnd0ActualDuration" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0IsRevisionDiscontinued" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="license_list"></ns0:properties>
<ns0:properties name="object_name" uiValue="......">
<ns0:values value="......"/></ns0:properties>
<ns0:properties name="priority" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="project_list"></ns0:properties>
<ns0:properties name="recipients"></ns0:properties>
<ns0:properties name="revision_limit" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="signoff_quorum" uiValue="-100">
<ns0:values value="-100"/></ns0:properties>
<ns0:properties name="fnd0Performer" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="gov_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="task_result" uiValue="Unset">
<ns0:values value="Unset"/></ns0:properties>
<ns0:properties name="task_template" uiValue="......">
<ns0:values value="xIlJeWDN5p7SJC"/></ns0:properties>
<ns0:properties name="viewed_by"></ns0:properties>
<ns0:properties name="parent_processes"></ns0:properties>
<ns0:properties name="fnd0InProcess" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0StartedTasks"></ns0:properties>
<ns0:properties name="named_acl" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="parent_task" uiValue="CY-FLW-014/..................">
<ns0:values value="QWkN69FA5p7SJC"/></ns0:properties>
<ns0:properties name="owning_project" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="last_mod_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="real_state" uiValue="Started">
<ns0:values value="Started"/></ns0:properties>
<ns0:properties name="owning_organization" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0EndDate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0LatestTargetOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="ip_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0PerformForm" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="fnd0Priority" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0StartDate" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:38+08:00"/></ns0:properties>
<ns0:properties name="job_name" uiValue="000022/A;1-...............1">
<ns0:values value="000022/A;1-...............1"/></ns0:properties>
<ns0:properties name="late_flag" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0LatestEPMTaskOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Instructions" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="wait_for_all_reviewers" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="wso_thread" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:38+08:00"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_string" uiValue="......">
<ns0:values value="......"/></ns0:properties>
<ns0:properties name="object_type" uiValue="Review Task">
<ns0:values value="EPMReviewTask"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="wNmJ_l7z5p7SJC" uid="wNmJ_l7z5p7SJC" className="TaskInbox" type="TasksToPerform">
<ns0:properties name="contents">
<ns0:values value="QarN69FA5p7SJC"/>
<ns0:values value="RtkJeWDN5p7SJC"/><ns0:uiValues>perform-signoffs</ns0:uiValues><ns0:uiValues>perform-signoffs</ns0:uiValues></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:48+08:00"/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_type" uiValue="Tasks To Perform">
<ns0:values value="TasksToPerform"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="object_string" uiValue="Tasks To Perform">
<ns0:values value="Tasks To Perform"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="RtkJeWDN5p7SJC" uid="RtkJeWDN5p7SJC" className="EPMTask" type="EPMPerformSignoffTask">
<ns0:properties name="object_type" uiValue="Perform Signoff Task">
<ns0:values value="EPMPerformSignoffTask"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="object_string" uiValue="perform-signoffs">
<ns0:values value="perform-signoffs"/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="02-Aug-2022 17:36">
<ns0:values value="2022-08-02T17:36:01+08:00"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="AWjJ_pMM5p7SJC" uid="AWjJ_pMM5p7SJC" className="Dataset" type="MSExcelX">
<ns0:properties name="process_stage_list">
<ns0:values value="QWkN69FA5p7SJC"/><ns0:uiValues>CY-FLW-014/..................</ns0:uiValues></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="fnd0IsCheckOutForSign" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="object_type" uiValue="MS ExcelX">
<ns0:values value="MSExcelX"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="fnd0IsSignable" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="revision_number" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="01-Aug-2022 10:44">
<ns0:values value="2022-08-01T10:44:14+08:00"/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="object_string" uiValue="......excel.xlsx">
<ns0:values value="......excel.xlsx"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="QWkN69FA5p7SJC" uid="QWkN69FA5p7SJC" className="EPMTask" type="EPMTask">
<ns0:properties name="creation_date" uiValue="26-Dec-2022 18:07">
<ns0:values value="2022-12-26T18:07:58+08:00"/></ns0:properties>
<ns0:properties name="due_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="ead_paragraph"></ns0:properties>
<ns0:properties name="fnd0ActualDuration" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0AssigneeOrigin" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="comments" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="backup_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="date_released" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="active_surrogate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="archive_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="attachments"></ns0:properties>
<ns0:properties name="fnd0InProcess" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0Assigner" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="fnd0EndDate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0LatestEPMTaskOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0LatestTargetOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Performer" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="fnd0Instructions" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="fnd0IsRevisionDiscontinued" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_organization" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="license_list"></ns0:properties>
<ns0:properties name="parent_task" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="fnd0Priority" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="project_list"></ns0:properties>
<ns0:properties name="wait_for_all_reviewers" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="ip_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="last_mod_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="recipients"></ns0:properties>
<ns0:properties name="priority" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="viewed_by"></ns0:properties>
<ns0:properties name="fnd0StartedTasks">
<ns0:values value="QWrN69FA5p7SJC"/>
<ns0:values value="QarN69FA5p7SJC"/><ns0:uiValues>......</ns0:uiValues><ns0:uiValues>perform-signoffs</ns0:uiValues></ns0:properties>
<ns0:properties name="late_flag" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="revision_limit" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="signoff_quorum" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="owning_project" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="gov_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0StartDate" uiValue="26-Dec-2022 18:08">
<ns0:values value="2022-12-26T18:08:01+08:00"/></ns0:properties>
<ns0:properties name="object_name" uiValue="CY-FLW-014/..................">
<ns0:values value="CY-FLW-014/.................."/></ns0:properties>
<ns0:properties name="wso_thread" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="named_acl" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="task_template" uiValue="CY-FLW-014/..................">
<ns0:values value="hsnJeWDN5p7SJC"/></ns0:properties>
<ns0:properties name="task_result" uiValue="Unset">
<ns0:values value="Unset"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:48+08:00"/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_string" uiValue="CY-FLW-014/..................">
<ns0:values value="CY-FLW-014/.................."/></ns0:properties>
<ns0:properties name="object_type" uiValue="Workflow Task">
<ns0:values value="EPMTask"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="QarN69FA5p7SJC" uid="QarN69FA5p7SJC" className="EPMTask" type="EPMPerformSignoffTask">
<ns0:properties name="active_surrogate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="archive_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="attachments"></ns0:properties>
<ns0:properties name="Fnd0EPMSignoff">
<ns0:values value="gCkN69FA5p7SJC"/><ns0:uiValues></ns0:uiValues></ns0:properties>
<ns0:properties name="creation_date" uiValue="26-Dec-2022 18:07">
<ns0:values value="2022-12-26T18:07:58+08:00"/></ns0:properties>
<ns0:properties name="due_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="backup_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="ead_paragraph"></ns0:properties>
<ns0:properties name="fnd0ActualDuration" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="comments" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="date_released" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0EndDate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0AssigneeOrigin" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0InProcess" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0Instructions" uiValue="Signoff team perform their signoffs.">
<ns0:values value="Signoff team perform their signoffs."/></ns0:properties>
<ns0:properties name="fnd0Assigner" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="last_mod_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="named_acl" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="fnd0IsRevisionDiscontinued" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0LatestEPMTaskOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0StartDate" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:45+08:00"/></ns0:properties>
<ns0:properties name="late_flag" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0LatestTargetOARTPN" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0PerformForm" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="fnd0Priority" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="gov_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="license_list"></ns0:properties>
<ns0:properties name="fnd0Performer" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="job_name" uiValue="000022/A;1-...............1">
<ns0:values value="000022/A;1-...............1"/></ns0:properties>
<ns0:properties name="fnd0StartedTasks"></ns0:properties>
<ns0:properties name="ip_classification" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="wait_for_all_reviewers" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="recipients"></ns0:properties>
<ns0:properties name="task_template" uiValue="perform-signoffs">
<ns0:values value="xwkJeWDN5p7SJC"/></ns0:properties>
<ns0:properties name="owning_project" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="parent_task" uiValue="......">
<ns0:values value="QWrN69FA5p7SJC"/></ns0:properties>
<ns0:properties name="wso_thread" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="parent_processes"></ns0:properties>
<ns0:properties name="real_state" uiValue="Started">
<ns0:values value="Started"/></ns0:properties>
<ns0:properties name="viewed_by"></ns0:properties>
<ns0:properties name="priority" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="task_result" uiValue="Unset">
<ns0:values value="Unset"/></ns0:properties>
<ns0:properties name="object_name" uiValue="perform-signoffs">
<ns0:values value="perform-signoffs"/></ns0:properties>
<ns0:properties name="project_list"></ns0:properties>
<ns0:properties name="owning_organization" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="signoff_quorum" uiValue="-100">
<ns0:values value="-100"/></ns0:properties>
<ns0:properties name="revision_limit" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="object_type" uiValue="Perform Signoff Task">
<ns0:values value="EPMPerformSignoffTask"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="process_stage_list"></ns0:properties>
<ns0:properties name="object_string" uiValue="perform-signoffs">
<ns0:values value="perform-signoffs"/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="28-Dec-2022 10:51">
<ns0:values value="2022-12-28T10:51:45+08:00"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="gCkN69FA5p7SJC" uid="gCkN69FA5p7SJC" className="Signoff" type="Signoff">
<ns0:properties name="active_surrogate" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="archive_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="archive_info" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="comments" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="creation_date" uiValue="26-Dec-2022 18:08">
<ns0:values value="2022-12-26T18:08:00+08:00"/></ns0:properties>
<ns0:properties name="fnd0DecisionRequired" uiValue="No">
<ns0:values value="Optional"/></ns0:properties>
<ns0:properties name="fnd0Performer" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="decision" uiValue="No Decision">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="fnd0Priority" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="backup_date" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="decision_date" uiValue="">
<ns0:values value="0001-01-01T00:00:00+00:00"/></ns0:properties>
<ns0:properties name="fnd0AssigneeOrigin" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0Assigner" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="group_member" uiValue="dba/DBA/admin (admin)">
<ns0:values value="wJoJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="last_mod_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="origin" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="origin_profile" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="originated_from" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="26-Dec-2022 18:08">
<ns0:values value="2022-12-26T18:08:00+08:00"/></ns0:properties>
<ns0:properties name="resource_pool" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="wFsJ_l7z5p7SJC" uid="wFsJ_l7z5p7SJC" className="User" type="User">
<ns0:properties name="license_level" uiValue="0">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="newstuff_folder" uiValue="Newstuff">
<ns0:values value="wJiJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="default_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="user_name" uiValue="admin">
<ns0:values value="admin"/></ns0:properties>
<ns0:properties name="user_projects"></ns0:properties>
<ns0:properties name="user_id" uiValue="admin">
<ns0:values value="admin"/></ns0:properties>
<ns0:properties name="home_folder" uiValue="Home">
<ns0:values value="wJgJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="person" uiValue="admin">
<ns0:values value="wFoJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="userinbox" uiValue="My Worklist">
<ns0:values value="wJvJ_l7z5p7SJC"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="wZiJ_pMM5p7SJC" uid="wZiJ_pMM5p7SJC" className="ItemRevision" type="ItemRevision">
<ns0:properties name="last_mod_date" uiValue="01-Aug-2022 10:44">
<ns0:values value="2022-08-01T10:44:14+08:00"/></ns0:properties>
<ns0:properties name="object_string" uiValue="000022/A;1-...............1">
<ns0:values value="000022/A;1-...............1"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="process_stage_list">
<ns0:values value="QWkN69FA5p7SJC"/><ns0:uiValues>CY-FLW-014/..................</ns0:uiValues></ns0:properties>
<ns0:properties name="revision_number" uiValue=" ">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="object_type" uiValue="Item Revision">
<ns0:values value="ItemRevision"/></ns0:properties>
<ns0:properties name="items_tag" uiValue="000022-...............1">
<ns0:values value="wVrJ_pMM5p7SJC"/></ns0:properties>
<ns0:properties name="fnd0IRDCUsed" uiValue="">
<ns0:values value=""/></ns0:properties>
<ns0:properties name="fms_tickets"></ns0:properties>
<ns0:properties name="has_variant_module" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="is_IRDC" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="view"></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="is_vi" uiValue="False">
<ns0:values value="0"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="AKpJ_pMM5p7SJC" uid="AKpJ_pMM5p7SJC" className="Dataset" type="DirectModel">
<ns0:properties name="last_mod_date" uiValue="01-Aug-2022 10:43">
<ns0:values value="2022-08-01T10:43:59+08:00"/></ns0:properties>
<ns0:properties name="object_type" uiValue="Direct Model">
<ns0:values value="DirectModel"/></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="fnd0IsSignable" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="fnd0IsCheckOutForSign" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="process_stage_list">
<ns0:values value="QWkN69FA5p7SJC"/><ns0:uiValues>CY-FLW-014/..................</ns0:uiValues></ns0:properties>
<ns0:properties name="revision_number" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="object_string" uiValue="JTModel.jt">
<ns0:values value="JTModel.jt"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="AkiJ_h285p7SJC" uid="AkiJ_h285p7SJC" className="Group" type="Group">
<ns0:properties name="object_full_name" uiValue="dba">
<ns0:values value="dba"/></ns0:properties>
<ns0:properties name="privilege" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="name" uiValue="dba">
<ns0:values value="dba"/></ns0:properties>
<ns0:properties name="description" uiValue="DataBase Administrator group.">
<ns0:values value="DataBase Administrator group."/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="AOuJ_pMM5p7SJC" uid="AOuJ_pMM5p7SJC" className="Dataset" type="MSWordX">
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="object_type" uiValue="MS WordX">
<ns0:values value="MSWordX"/></ns0:properties>
<ns0:properties name="object_string" uiValue="......word.docx">
<ns0:values value="......word.docx"/></ns0:properties>
<ns0:properties name="fnd0IsSignable" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0IsCheckOutForSign" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="process_stage_list">
<ns0:values value="QWkN69FA5p7SJC"/><ns0:uiValues>CY-FLW-014/..................</ns0:uiValues></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="revision_number" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="01-Aug-2022 10:44">
<ns0:values value="2022-08-01T10:44:08+08:00"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="wxuJ_pMM5p7SJC" uid="wxuJ_pMM5p7SJC" className="Dataset" type="CAEAnalysisDS">
<ns0:properties name="owning_site" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="fnd0IsCheckOutForSign" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="object_type" uiValue="CAE Analysis">
<ns0:values value="CAEAnalysisDS"/></ns0:properties>
<ns0:properties name="object_string" uiValue="......pdf.pdf">
<ns0:values value="......pdf.pdf"/></ns0:properties>
<ns0:properties name="owning_user" uiValue="admin (admin)">
<ns0:values value="wFsJ_l7z5p7SJC"/></ns0:properties>
<ns0:properties name="object_desc" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties>
<ns0:properties name="owning_group" uiValue="dba">
<ns0:values value="AkiJ_h285p7SJC"/></ns0:properties>
<ns0:properties name="revision_number" uiValue="1">
<ns0:values value="1"/></ns0:properties>
<ns0:properties name="last_mod_date" uiValue="01-Aug-2022 10:43">
<ns0:values value="2022-08-01T10:43:48+08:00"/></ns0:properties>
<ns0:properties name="checked_out" uiValue=" ">
<ns0:values value=" "/></ns0:properties>
<ns0:properties name="process_stage_list">
<ns0:values value="QWkN69FA5p7SJC"/><ns0:uiValues>CY-FLW-014/..................</ns0:uiValues></ns0:properties>
<ns0:properties name="release_status_list"></ns0:properties>
<ns0:properties name="fnd0IsSignable" uiValue="">
<ns0:values isNull="1" value=""/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="xohJeWDN5p7SJC" uid="xohJeWDN5p7SJC" className="EPMTaskTemplate" type="EPMPerformSignoffTaskTemplate">
<ns0:properties name="template_name" uiValue="perform-signoffs">
<ns0:values value="perform-signoffs"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="xskJeWDN5p7SJC" uid="xskJeWDN5p7SJC" className="EPMTaskTemplate" type="EPMSelectSignoffTaskTemplate">
<ns0:properties name="template_name" uiValue="select-signoff-team">
<ns0:values value="select-signoff-team"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="xIlJeWDN5p7SJC" uid="xIlJeWDN5p7SJC" className="EPMTaskTemplate" type="EPMReviewTaskTemplate">
<ns0:properties name="template_name" uiValue="......">
<ns0:values value="......"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="xAsJeWDN5p7SJC" uid="xAsJeWDN5p7SJC" className="EPMTaskTemplate" type="EPMReviewTaskTemplate">
<ns0:properties name="template_name" uiValue="......">
<ns0:values value="......"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="hsnJeWDN5p7SJC" uid="hsnJeWDN5p7SJC" className="EPMTaskTemplate" type="EPMTaskTemplate">
<ns0:properties name="template_name" uiValue="CY-FLW-014/..................">
<ns0:values value="CY-FLW-014/.................."/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="wJoJ_l7z5p7SJC" uid="wJoJ_l7z5p7SJC" className="GroupMember" type="GroupMember">
<ns0:properties name="ga" uiValue="False">
<ns0:values value="0"/></ns0:properties>
<ns0:properties name="user_name" uiValue="admin">
<ns0:values value="admin"/></ns0:properties></ns0:dataObjects>
<ns0:dataObjects objectID="wJgJ_l7z5p7SJC" uid="wJgJ_l7z5p7SJC" className="Folder" type="Fnd0HomeFolder"></ns0:dataObjects>
<ns0:dataObjects objectID="wJiJ_l7z5p7SJC" uid="wJiJ_l7z5p7SJC" className="Folder" type="Newstuff Folder"></ns0:dataObjects>
<ns0:dataObjects objectID="wFoJ_l7z5p7SJC" uid="wFoJ_l7z5p7SJC" className="Person" type="Person"></ns0:dataObjects>
<ns0:dataObjects objectID="wJvJ_l7z5p7SJC" uid="wJvJ_l7z5p7SJC" className="User_Inbox" type="User_Inbox"></ns0:dataObjects>
<ns0:dataObjects objectID="wVrJ_pMM5p7SJC" uid="wVrJ_pMM5p7SJC" className="Item" type="Item"></ns0:dataObjects></ns0:ServiceData>